version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    
  celery-worker:
    build: .
    command: celery -A src.celery_tasks.c_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      
  celery-flower:
    build: .
    command: celery -A src.celery_tasks.c_app flower --port=5555
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
