"""add roles to users

Revision ID: 2f3378b38d47
Revises: 3758f1898ddf
Create Date: 2025-08-04 20:35:25.448165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2f3378b38d47'
down_revision: Union[str, Sequence[str], None] = '3758f1898ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add the column as nullable first
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), nullable=True))
    
    # Step 2: Update existing users with a default role
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # Step 3: Make the column NOT NULL now that all rows have values
    op.alter_column('users', 'role', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
