"""change published_date to date type

Revision ID: 3758f1898ddf
Revises: c70387d2f053
Create Date: 2025-08-01 17:03:37.817555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3758f1898ddf'
down_revision: Union[str, Sequence[str], None] = 'c70387d2f053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to convert VARCHAR to DATE with explicit casting
    op.execute("ALTER TABLE books ALTER COLUMN published_date TYPE DATE USING published_date::date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'published_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
